### ISSUE TITLE
Assessment, Automated Security Evaluation & Testing, and Continous Authorization Pilot

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/blossom-oscal#3]
As a BLOSSOM agency stakeholder, in order to understand how BLOSSOM conforms to best practice with federal cybersecurity standards, I want to see the pilot of simulated assessment, automated security evaluation and testing to validate system implementation and assessment for an authorization. As an outcome of this, I want to see recommendations on how to take this pilot in a continuous authorization context supported by the other key objectives.

- [x] usnistgov/blossom-oscal#5
- [x] usnistgov/blossom-archived#80
- [x] usnistgov/blossom-archived#76
- [x] usnistgov/blossom-oscal#4
- [x] usnistgov/blossom-oscal#6
- [ ] From the baseline, select relevant sample controls
- [ ] Document controls in an OSCAL system security plan and commit them to this repo (or new submodule)
- [ ] Research and determine best way to automate security eval and testing of said controls
- [ ] Implement security automation testing to support controls
